### ISSUE TITLE
Progress bars

### ISSUE THREAD

**Issue by whatsnewsaes** [codesummit/Sparkplug#71]
Thanks codepen http://codepen.io/search?q=progress+bar&limit=all&order=popularity&depth=everything&show_forks=false
![screen shot 2015-04-22 at 9 04 15 am](https://cloud.githubusercontent.com/assets/2118456/7274925/d0fa9dc6-e8ce-11e4-94ef-f8266e3f77e0.png)

**Comment by gr33k01** [comment]
https://github.com/CodesummitGoats/Sparkplug-Framework/commit/4f09ef2ad154e563819ccd58dcf72956d159dbc1
